function [EEG,p] = mv_load_random_set(field)
%%[EEG,p] = mv_load_random_set(field)
% This function loads a random altready Filtered Set and checks whether the
% given field has been cleaned already
% Available fields are:
%   'badComp'
%   'badChannel'
%   'badCont'
%   'badTrial'
strList = {'badComp','badChannel','badCont','badTrial'};
if ~any(cellfun(@(x)strcmp(x,field),strList))
    help mv_load_random_set
    error('Not recogniyed field: %s',field)
end

flags = mv_check_folderstruct;
% get a random file
idxDatasetAll = (find(flags.raw & flags.(field)==0 & flags.setFilt) );
% idxDatasetAll = setDiff(idxDatasetAll);
%if strcmp(input('fw or lk?','s'),'lk')
%    idxDatasetAll = idxDatasetAll(idxDatasetAll< 25);
%else
%    idxDatasetAll = idxDatasetAll(idxDatasetAll>= 25);
%end

idxDataset = idxDatasetAll(randi(length(idxDatasetAll),1));
if strcmp(field,'badCont')
fprintf('%i out of %i are awaiting approval and %i are already approved/checked, random Dataset to clean was chosen \n',sum(flags.raw & flags.badCont==1),sum(flags.raw),sum(flags.raw & flags.badCont==2))
end
% generate using the path generated by mv_check_folderstruct
p = mv_generate_paths(flags.path{idxDataset});
% load the set
EEG = mv_load_set2(p,1);

end