function [sT2] = behav_sT_removeFields(sT)
tmp ={'startFirstPathIdx',...
    'endFirstPathIdx',...
    'turnStartIndIdx',...
    'turnEndIndIdx',...
    'startSecondPathIdx',...
    'endSecondPathIdx',...
    'fadeIndIdx',...
    'lastIdxRaw',...
    'secondArm',...
    'firstArm',...
    'arrowAngleInitial',...
    'chosenArrowAngle',...
    'EndPosX',...
    'EndPosZ',...
    'calculatedFirstArm',...
    'calculatedSecondArm',...
    'arrowOffsetRot',...
    'EndPosXVar',...
    'EndPosZVar',...
    'gamma',...
    'arrowAngleOptimalTAbs',...
    'arrowAngleOptimalNonTAbs',...
    'chosenArrowAngleNorm',...
    'chosenArrowAngleAbs'};
sT2 = sT;
sT2 = rmfield(sT2,tmp);

%% Old version was to keep the fields
% tmp ={'condition',...
%     'numTrials',...
%     'trialDuration',...
%     'trialNumbers',...
%     'turningAnglePlanned',...
%     'degreesTurned',...
%     'arrowAngleOptimalT',...
%     'arrowAngleOptimalNonT',...
%     'errors_T',...
%     'errors_NT'...
%     'errors_T_VarPos'...
%     'errors_NT_VarPos'...
%     'turningAnglePerfect'};   
% for k = tmp
%    sT2.(k{:}) = sT.(k{:}); 
% end

end